[package]
name = "theorem-prover-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
divan = { version = "0.1.17", optional = true }
flexi_logger = "0.29.8"
indexmap = "2.8.0"
itertools = "0.14.0"
log = "0.4.26"
maplit = "1.0.2"
mimalloc = { version = "0.1.43", default-features = false }
peg = "0.8.5"
regex = "1.11.1"
rlimit = "0.10.2"
rustc-hash = "2.1.1"
thiserror = "2.0.12"
typed-arena = "2.0.2"
unicode-normalization = "0.1.24"

[dev-dependencies]
insta = "1.42.2"
test-case = "3.3.1"

[features]
bench = ["divan"]

[[bench]]
name = "bench"
harness = false
required-features = ["bench"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
# pedantic
similar_names = "allow"
enum_glob_use = "allow"
too_many_lines = "allow"
missing_panics_doc = "allow"
missing_errors_doc = "allow"
must_use_candidate = "allow"
match_wildcard_for_single_variants = "allow"
module_name_repetitions = "allow"
inline_always = "allow"
# nursery
missing_const_for_fn = "allow"
