[package]
name = "theorem-prover-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
divan = { version = "0.1.21", optional = true }
itertools = "0.14.0"
log = "0.4.27"
log4rs = "1.3.0"
maplit = "1.0.2"
mimalloc = "0.1.48"
peg = "0.8.5"
regex = "1.11.2"
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_with = "3.14.0"
serde_yml = "0.0.12"
thiserror = "2.0.16"
typed-arena = "2.0.2"
unicode-normalization = "0.1.24"

[dev-dependencies]
insta = "1.43.1"
tempfile = "3.21.0"
test-case = "3.3.1"

[features]
bench = ["divan"]

[[bench]]
name = "bench"
harness = false
required-features = ["bench"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
# pedantic
similar_names = "allow"                      # it's ok to have similar names
enum_glob_use = "allow"                      # want to use `use Formula::*;` for example
too_many_lines = "allow"                     # it's ok to have long code
match_wildcard_for_single_variants = "allow" # want to use `_` in matches
inline_always = "allow"                      # want to use `#[inline(always)]`
# nursery
cognitive_complexity = "allow" # it's ok to have complex code
# restriction
absolute_paths = "warn" # avoid full paths
allow_attributes = "warn" # use `#[expect(...)]` instead of `#[allow(...)]`
