[package]
name = "theorem-prover-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_variant_type = "0.3.1"
maplit = "1.0.2"
once_cell = "1.18.0"
peg = "0.8.1"
unicode-normalization = "0.1.22"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
