[package]
name = "theorem-prover-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_variant_type = "0.3.1"
indexmap = "2.0.2"
itertools = "0.11.0"
maplit = "1.0.2"
mimalloc = "0.1.39"
peg = "0.8.1"
regex = "1.9.5"
rustc-hash = "1.1.0"
strum = { version = "0.25.0", features = ["derive"] }
typed-arena = "2.0.2"
unicode-normalization = "0.1.22"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
