[package]
name = "theorem-prover-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
divan = { version = "0.1.21", optional = true }
itertools = "0.14.0"
log = "0.4.28"
log4rs = "1.4.0"
maplit = "1.0.2"
mimalloc = "0.1.48"
peg = "0.8.5"
regex = "1.11.2"
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_yaml_bw = "2.2.0"
thiserror = "2.0.16"
typed-arena = "2.0.2"
unicode-normalization = "0.1.24"

[dev-dependencies]
insta = "1.43.2"
tempfile = "3.22.0"
test-case = "3.3.1"

[features]
bench = ["divan"]

[[bench]]
name = "bench"
harness = false
required-features = ["bench"]

[profile.release]
codegen-units = 1
lto = true

[profile.profiling]
inherits = "release"
debug = true

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
# pedantic
similar_names = "allow" # it's ok to have similar names
enum_glob_use = "allow" # want to use `use Formula::*;` for example
too_many_lines = "allow" # it's ok to have long code
match_wildcard_for_single_variants = "allow" # want to use `_` in matches
inline_always = "allow" # want to use `#[inline(always)]`
# nursery
cognitive_complexity = "allow" # it's ok to have complex code
# restriction
absolute_paths = "warn" # avoid full paths
allow_attributes = "warn" # use `#[expect(...)]` instead of `#[allow(...)]`
as_conversions = "warn" # avoid `as`
assertions_on_result_states = "warn" # use `.unwrap()` instead of `assert!(result.is_ok())`
empty_enum_variants_with_brackets = "warn" # avoid unnecessary brackets
empty_structs_with_brackets = "warn" # avoid unnecessary brackets
get_unwrap = "warn" # use [] instead of `.get().unwrap()`
if_then_some_else_none = "warn" # use `bool::then_some` or `bool::then` instead of `if ... { Some(..) } else { None }`
integer_division = "warn" # avoid integer division
large_include_file = "warn" # avoid too large `include_str!`
map_with_unused_argument_over_ranges = "warn" # use `repeat` and `take` instead of `map(|_| ...)`
missing_assert_message = "warn" # must have messages in `assert!()`
needless_raw_strings = "warn" # avoid unnecessary raw strings
panic = "warn" # avoid `panic!()`
partial_pub_fields = "warn" # avoid partial public fields
print_stderr = "warn" # avoid `eprintln!()`
print_stdout = "warn" # avoid `println!()`
redundant_type_annotations = "warn" # avoid redundant type annotations
ref_patterns = "warn" # avoid `ref`
rest_pat_in_fully_bound_structs = "warn" # avoid unnecessary `..`
return_and_then = "warn" # use `?` instead of `and_then`
str_to_string = "warn" # use `into` or `to_owned` instead of `to_string`
string_lit_chars_any = "warn" # use `matches!` instead of `.chars().any(...)`
tests_outside_test_module = "warn" # put tests in `#[cfg(test)]`
unneeded_field_pattern = "warn" # use `..` instead of `_`
use_debug = "warn" # avoid debug formatting

[lints.rust]
explicit-outlives-requirements = "warn" # avoid unnecessary lifetime bounds
redundant-lifetimes = "warn" # avoid redundant lifetime parameters

[lints.rustdoc]
unescaped_backticks = "warn" # avoid unescaped backticks in doc comments
